// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkxnmlilkzvncandzgdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBreG5tbGlsa3p2bmNhbmR6Z2RrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MTQyMjcsImV4cCI6MjA2ODE5MDIyN30.SOE_fVNHCM7rUj2z7wf8LtC2y5BxXo4sQ4dSiThz9fs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});